### ISSUE TITLE
snapshot during training

### ISSUE THREAD

**Issue by Wulin-Tan** [danbider/lightning-pose#176]
Hi, LP team
in DLC training, some snapshots would be saved every few iterations. and we can make use of certain snapshots for prediction. 

Is there any function to do this in LP? 

let's say I train the model for 500 epochs. and finally I found that 300 epochs would be the best. Then I would like to pick 300 epochs model for later use, instead of training the model from beginning to 300 epochs.

in the LP, the prediction py file has a line:
```
model = load_model_from_checkpoint(cfg=cfg, ckpt_file=ckpt_file, eval=True)
```
that means I can load the specific ckpt file, I think if we can save the ckpt file every few steps like 50/100/200, that would be better.

**Comment by themattinthehatt** [comment]
I updated the code to allow you to do this. To enable this feature, add the following to your config file:
```
training:
   ckpt_every_n_epoch: 50
```
This will save a checkpoint every 50 epochs; update to whatever value you'd like, but note that `training.check_val_every_n_epoch` should evenly divide whichever number you choose. 

Please let me know if this works for you, and I'll close this issue.

**Comment by Wulin-Tan** [comment]
Hi, @themattinthehatt 
I tried it on LP 1.4.0 like:
```
  min_epochs: 30
  max_epochs: 30
  log_every_n_steps: 10
  check_val_every_n_epoch: 5
  gpu_id: 0
  rng_seed_data_pt: 0
  rng_seed_model_pt: 0
  lr_scheduler: multisteplr
  lr_scheduler_params:
    multisteplr:
      milestones:
      - 150
      - 200
      - 250
      gamma: 0.5
  ckpt_every_n_epochs: 10
```
but it did not work. only the final ckpt was saved. I listed all the ckpt files but only got one:
```
/root/autodl-tmp/DLC_LP/outputs/2024-06-18/12-43-09/tb_logs/DLC_LP/version_0/checkpoints/epoch=29-step=300.ckpt
```
any suggestion?
